pyms:
  services:
    service_discovery:
      service: "service.ServiceDiscoveryConsulBasic"
      host: "localhost"
      autoregister: true
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python MS My personal Service Discovery check one"
    APPLICATION_ROOT: ""